apiVersion: apps/v1
kind: Deployment
metadata:
  name: sale-description-generator
  namespace: sale-description-generator
  labels:
    app: sale-description-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sale-description-generator
  template:
    metadata:
      labels:
        app: sale-description-generator
    spec:
      containers:
      - name: sale-description-generator
        image: ghcr.io/brotherlogic/sale-description-generator:0.2.6 # {"$imagepolicy": "sale-description-generator:sale-description-generator"}
        ports:
        - containerPort: 50051
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-api-key
              key: GEMINI_API_KEY
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
