apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: sale-description-generator
  namespace: sale-description-generator
spec:
  image: ghcr.io/brotherlogic/sale-description-generator
  interval: 10m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: sale-description-generator
  namespace: sale-description-generator
spec:
  imageRepositoryRef:
    name: sale-description-generator
  policy:
    semver:
      range: '>=0.0.1'
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: sale-description-generator
  namespace: sale-description-generator
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
    push:
      branch: main
  update:
    path: ./my-cluster/apps/sale-description-generator
    strategy: Setters
