apiVersion: v1
kind: Service
metadata:
  name: sale-description-generator
  namespace: sale-description-generator
  labels:
    app: sale-description-generator
spec:
  type: NodePort
  selector:
    app: sale-description-generator
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
      nodePort: 30050
