---
- name: Update apt cache and upgrade packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install basic utilities
  apt:
    name:
      - curl
      - git
      - htop
      - rsync
      - vim
      - golang-go
    state: present

- name: Install chezmoi
  shell: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/local/bin
  args:
    creates: /usr/local/bin/chezmoi
